### ISSUE TITLE
Sbt plugin for project setup

### ISSUE THREAD

**Issue by bambuchaAdm** [ltbs/uniform-scala#11]
Project setup is quite complicated and require some changes in list of options. Providing plugin for single line enabling uniform in project would be noticeable time saver.

**Comment by hmrclt** [comment]
What would this plugin actually do?

**Comment by bambuchaAdm** [comment]
Add `scalac` flag for 2.11
Add compiler plugin
Provide variables with same version for every component to dependency management

**Comment by hmrclt** [comment]
I'm not likely to build this as I don't think the setup is necessarily much more complex than adding an sbt plugin to your project.
