### ISSUE TITLE
mill investigation

### ISSUE THREAD

**Issue by hmrclt** [ltbs/uniform-scala#134]
There are lots of problems with using SBT for the cross-building. 

Investigate switching over to mill for the build

**Comment by hmrclt** [comment]
Core JVM modules building under mill branch with cross scala versions.

The syntax seems a bit more obvious than with SBT.

**Comment by ltbs** [comment]
Closing this down. Mill seems to work fairly well but we want to avoid doing anything too non-standard that could become a barrier to collaboration now this project is part of typelevel.
