### ISSUE TITLE
Leap ahead with subjourneys

### ISSUE THREAD

**Issue by hmrclt** [ltbs/uniform-scala#276]
At present leap-ahead behaves counter-intuitively when encountering listing pages. 

A better implementation would be as follows - 

1. link on CYA page has a param that stores the referring page (the CYA page) and the landing page (the one you're editing) into the state
2. the first page after the landing page that is not a subpage of the landing page allows the journey to leap ahead to the referring page

I think this should get around the problems with listing pages, allow subjourneys with their own CYA pages, etc.

**Comment by ltbs** [comment]
resolved.
