### ISSUE TITLE
Investigation: Should we be targeting the IO monad rather than Future

### ISSUE THREAD

**Issue by hmrclt** [ltbs/uniform-scala#50]
At present the common web interactions are assuming that we are working with Futures, though this is mainly for use with the Play Interpreter. 

Considering that the cats effect IO is considered better and can be converted into a Future should we be targeting that instead? Or perhaps find a way to avoid choosing an effect until the final interpreter?

**Comment by ltbs** [comment]
Most people who I have asked would prefer to remain targeting Future for the moment.
